### ISSUE TITLE
Weird error on uploading 

### ISSUE THREAD

**Issue by scottgallant** [forestryio/docs#12]
Uploaded this site and got this crazy error:

https://github.com/opattison/olivermakes

<img width="1107" alt="screen shot 2016-06-03 at 11 47 02 am" src="https://cloud.githubusercontent.com/assets/776019/15782510/017a37c4-2981-11e6-9a4d-686ff2b054ed.png">

The site was too big (I got a 250MB max error message before this), so I deleated some images and re-tried it.  I'm getting a success message, but the site isn't in my dashboard.

**Comment by jpatters** [comment]
How big was the site?

**Comment by jpatters** [comment]
Cloudflare limit is 100MB
https://support.cloudflare.com/hc/en-us/articles/201303340-How-can-I-change-the-client-maximum-upload-size-

**Comment by scottgallant** [comment]
oh. it was 260MB. but I cut it down to around 200MB.

**Comment by jpatters** [comment]
i thought we set our limit to 250MB. but the 200MB still wouldn't have worked

**Comment by scottgallant** [comment]
Ours is 250.  so I cut it down less than that but got this error.

**Comment by jpatters** [comment]
yes. thats because the cloudflare limit is 100MB as stated above

**Comment by scottgallant** [comment]
yeah, well that defeats the purpose of our limit. What should we do?

**Comment by jpatters** [comment]
im not sure. i'll have to think about it. we've been thinking of ditching cloudflare. maybe its time to do that
