### ISSUE TITLE
GH pages - clear up confusion around they source and hosting 

### ISSUE THREAD

**Issue by scottgallant** [forestryio/docs#13]

**Comment by AdamLeBlanc** [comment]
Is the confusion people are having that they try to set the source as master, than also deploy to master?

Assuming the answer to this is that we build the site, and deploy to a branch. So we'd be overwriting the source if we pushed the hosting version and source to the same place? Also, if they really want github pages (or some other thing) to do the build, they can just commit without setting up a host.
