### ISSUE TITLE
What does Forestry change?

### ISSUE THREAD

**Issue by jpatters** [forestryio/docs#15]
1. Comments in _config.yaml. We add `vendor` to the list of exclusions so that it works with our build process. Ruby does not offer a solution for preserving comments or formatting when parsing and dumping yaml. The fields may also be rearranged. (we could get rid of this)
2. Comments and formatting will also be removed from frontmatter for the reason stated above. Frontmatter may also be reordered (we could probably fix this).
3. Line endings will be normalized to unix line endings. This is so we can consistently display content in the different content editors.
4. Spacing and code formatting may be changed in an edited file. This is because the content editors will apply their own spacing and code formatting rules when saving a file.
5. New images will be uploaded into `/assets/images`. Existing images will be untouched. It is really hard to guess where these should go so we don't. We just put everything into an images folder.
6. New files (other than images) will be uploaded into `/assets/files`. Existing files will be untouched.
7. Image paths in the body of pages/posts will be normalized to absolute paths. When a site is imported into Forestry we replace image paths with paths to the site images that we store in S3. This is so that you can see your images in the WYSIWYG editor and in the frontmatter fields. When we write the content pages back out when we compile the site, it is hard to know what the original path was since the images could have changed. So we just normalize them all to absolute paths.

That's everything I can think of now. I'll update this as I think of things

**Comment by jpatters** [comment]
Just published changes that take number 1 completely out of the equation

**Comment by jpatters** [comment]
We could also change the image upload directory to something like `/forestryio/images` so it is more obvious what is going on

**Comment by scottgallant** [comment]
I like that idea alot. What if we gave them an option to choose an images directory?

**Comment by jpatters** [comment]
Yeah, i was thinking of that as well. It could be a good thing but we don't want to end up with a long setup process either.

**Comment by scottgallant** [comment]
I like the idea of defaulting to `/forestryio/images` but in the settings they could change it to whatever they want.

**Comment by scottgallant** [comment]
Images - allow the user to choose a directory
Only write out the updated files
Go back to reading projects directly

**Comment by AdamLeBlanc** [comment]
Think this was already done
