### ISSUE TITLE
Document the purpose of the .forestryio file

### ISSUE THREAD

**Issue by jpatters** [forestryio/docs#22]
We add a `.forestryio` file to the root folder of the deployment destination to signal to us that it is ok to publish there. If a user tries to publish to a bucket/folder that already has content in it, we tell them that it has to be empty before we can publish. This is to prevent us overwriting something that we shouldn't. To signal that it is ok to publish in subsequent publishes, we add the `.forestryio` file. We check for that file before publishing. If it exists, we publish.

**Comment by scottgallant** [comment]
@dpscinto in FAQ "Why was a .forestryio file added to my project"
