### ISSUE TITLE
 CMS Sidebar

### ISSUE THREAD

**Issue by scottgallant** [forestryio/docs#33]

**Comment by AdamLeBlanc** [comment]
Why is this under setup, what part of the setup involves the sidebar? (Assuming you mean the part of the CMS with menus, and the directories)

**Comment by scottgallant** [comment]
I was just thinking it would be good to explain what ends up where.  that pages, posts end up the top (I think), collections(jekyll)/sections(hugo) follow, that navs are supported in Hugo but not jekyll. what chunks are, etc..

**Comment by jpatters** [comment]
They are in alphabetical order FYI

**Comment by AdamLeBlanc** [comment]
I don't know. It seems pretty unnecessary/overly verbose.  We already have docs on everything in the sidebar, it seems overkill to have a doc on the sidebar.

**Comment by chrisdmacrae** [comment]
This is lightly covered in the managing content docs.
