### ISSUE TITLE
 Data files

### ISSUE THREAD

**Issue by scottgallant** [forestryio/docs#35]

**Comment by AdamLeBlanc** [comment]
Do you mean the markdown files?

**Comment by jpatters** [comment]
nope. the files that go in _data (jekyll) or data (hugo)

**Comment by AdamLeBlanc** [comment]
Forestry puts these in the chunks directory right? (I've honestly never used data files)

**Comment by jpatters** [comment]
nope. we call them chunks but they stay in the _data (jekyll) or data (hugo) directory
