### ISSUE TITLE
Menus

### ISSUE THREAD

**Issue by scottgallant** [forestryio/docs#36]

**Comment by AdamLeBlanc** [comment]
What needs to be covered here? We already have a doc on menus, do you just mean how to actually make menus in a hugo project?

**Comment by jpatters** [comment]
That would be good.

**Comment by dpscinto** [comment]
@scottgallant title Hugo Menus?

**Comment by scottgallant** [comment]
@dpscinto yessir

**Comment by jpatters** [comment]
@dpscinto this one too: https://forestry.io/sites/g47yihqnkc4uiw/pages/editing-content-editing-menus-md
Not sure why there are 2 docs

**Comment by scottgallant** [comment]
One is for the end-user (in editing content) and one is for the dev (in setting up a site)
