### ISSUE TITLE
Uploading files

### ISSUE THREAD

**Issue by scottgallant** [forestryio/docs#53]

**Comment by AdamLeBlanc** [comment]
What is this referring to? We already have docs for all the different kinds of situations you can upload a file (making a site, images). Anything else I'm forgetting?

**Comment by jpatters** [comment]
You can also upload files, not just images

**Comment by scottgallant** [comment]
Like a PDF file or something.

**Comment by AdamLeBlanc** [comment]
Really?? I honestly don't even know where you do this from.

**Comment by jpatters** [comment]
exact same place as images. it says upload file unless you upload an image.

**Comment by AdamLeBlanc** [comment]
This only works for frontmatter though, correct?

**Comment by chrisdmacrae** [comment]
This is now documented as part of media management & in the media manager blog post
