### ISSUE TITLE
Support for Gulp and Grunt

### ISSUE THREAD

**Issue by scottgallant** [forestryio/docs#81]
Explain how you need to keep all of your compiled assets under version control...and describe how eventually, we'll support this.

**Comment by envygeeks** [comment]
You don't though?  I know the context of the example is out of the way but take Jekyll-Assets for example, we only keep non-compiled assets in the version control system, the rest of it is generated on the fly, this is how most users who use that system do it to (if they do it right) they should have a folder without all this stuff and then the final result shouldn't go anywhere but in the published folder.

Talk about Git craziness :P
